experiment:
  name: "apartemnts_katowice_prices"

data:
  target_col: "price_per_m"          

feature_selection:
  include: ["market", "building_age", "area", "rooms_num", "building_floors_num", "floor_num", "building_material", "construction_status", "district", 'balcony', 'separate_kitchen', 'air_conditioning','roller_shutters', 'dishwasher', 'garage','anti_burglary_door', 'basement', 'entryphone','garden', 'internet', 'monitoring', 'terrace', 'alarm', 'lift', 'closed_area']

xgboost:
  max_depth: 8
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.9
  n_estimators: 800
  reg_lambda: 1.0

training:
  test_size: 0.2
  random_state: 1
  early_stopping_rounds: 50
  eval_metric: rmsle
  tune_n_iter: 40
  cv_splits: 5
  random_state: 1

